version: '2'
services:
  web:
    container_name: wordroot_web
    build: .
    environment:
     - IS_RUNNING_IN_CONTAINER=yes
    volumes:
     - .:/wordroot
    ports:
     - "80:80"
    links:
     - db
  db:
    image: sameersbn/postgresql:9.6-2
    container_name: wordroot_db
    environment:
     - DB_USER=wordroot_user
     - DB_PASS=weak_password
     - DB_NAME=wordroot_database,wordroot_test_database
    volumes:
     - wordroot_data:/var/lib/postgresql/data
volumes:
  wordroot_data: