version: '2'
services:
  web:
    container_name: wordroot_web
    build: .
    environment:
     - IS_RUNNING_IN_CONTAINER=yes
    volumes:
     - .:/wordroot
    ports:
     - "80:80"       # Production
     - "8000:8000"   # Dev
     - "9009:9009"   # Clojure REPL
     - "33215:33215" # Resource reloading
    links:
     - db
  db:
    image: sameersbn/postgresql:9.6-2
    container_name: wordroot_db
    environment:
     - DB_USER=wordroot_user
     - DB_PASS=weak_password
     - DB_NAME=wordroot_database,wordroot_test_database,wordroot_dev_database
    volumes:
     - wordroot_data:/var/lib/postgresql
     - wordroot_data:/wordroot-data
volumes:
  wordroot_data: