version: '2'
services:
  web:
    container_name: wordroot_web
    build: .
    volumes:
     - .:/wordroot
    ports:
     - "8000:8000"
    links:
     - db
  db:
    image: postgres
    container_name: wordroot_db
    environment:
     - POSTGRES_USER=wordroot_user
     - POSTGRES_PASSWORD=weak_password
     - POSTGRES_DB=wordroot_database
    volumes:
     - wordroot_data:/var/lib/postgresql/data
volumes:
  wordroot_data: