version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    links:
     - db
  db:
    image: postgres
    environment:
     - POSTGRES_USER=wordroot_user
     - POSTGRES_PASSWORD=weak_password
     - POSTGRES_DB=wordroot_database