DROP TABLE IF EXISTS words CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS roots CASCADE;
DROP TABLE IF EXISTS word_parts CASCADE;
DROP TABLE IF EXISTS word_parts_roots CASCADE;
